spring.application.name=backend-app-gastos

spring.datasource.url=jdbc:postgresql://localhost:5432/gastos_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080

application.security.jwt.secret-key=586B633834416E396D7436753879382F423F4428482B4C6250655367566B5970
application.security.jwt.expiration=900000
application.security.jwt.cookie-name=jwt-cookie

application.security.jwt.refresh-token-expiration=1296000000
application.security.jwt.refresh-token.cookie-name=refresh-jwt-cookie

#spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
#spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
#spring.security.oauth2.client.registration.google.scope=openid,profile,email
#spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
#spring.security.oauth2.client.registration.google.client-name=Google

